<?php

/**
 * @file
 * Contains migration_boilerplate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\MigrateSkipRowException;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_help().
 */
function aetg_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migration_boilerplate module.
    case 'help.page.migration_boilerplate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 Migration Boilerplate Code') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migrate_prepare_row().
 */
function aetg_migration_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  // Content Types we are not importing / skipping.
  $skip_types = [
    // Put stuff here.
  ];

  // Fields to skip for now.
  $skip_fields = [
    // Put stuff here.
  ];

  // Entity types to skip for now.
  $entity_skip = [
    // Put stuff here.
  ];

  // Vocab Skip.
  $vocab_skip = [
    // Put stuff here.
  ];

  // Skip vocab.
  if (in_array($row->getSourceProperty('machine_name'), $vocab_skip)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Skip content types.
  if (in_array($row->getSourceProperty('bundle'), $skip_types)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Skip content types.
  if (in_array($row->getSourceProperty('type'), $skip_types)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Skip fields.
  if (in_array($row->getSourceProperty('field_name'), $skip_fields)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Skip entity types.
  if (in_array($row->getSourceProperty('instances')[0]['entity_type'], $entity_skip)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Skip entity types.
  if (in_array($row->getSourceProperty('entity_type'), $entity_skip)) {
    // This makes it so we don't need to reprocess the row.
    throw new MigrateSkipRowException('', TRUE);
  }

  // Do various tasks based on the migration id.
  switch ($migration->id()) {

    case 'upgrade_d7_field':
      // Move a field to a new type / bundle example.
      $instances = $row->getSourceProperty('instances');
      switch ($instances[0]['bundle']) {
        case 'OLD_BUNDLE':
          $instances[0]['bundle'] = 'NEW_BUNDLE';
          // Merge fields to person type.
          $row->setSourceProperty('instances', $instances);
          break;
      }
      break;

    case 'upgrade_d7_node_type':
      // Change the content type name example.
      switch ($row->getSourceProperty('type')) {
        case 'OLD_NAME':
          $row->setSourceProperty('name', 'NEW_NAME');
          break;
      }
      break;

    case 'upgrade_d7_field_instance':
    case 'upgrade_d7_field_formatter_settings':
    case 'upgrade_d7_field_instance_widget_settings':

      // Move a field to a new type / bundle example continued.
      $instances = $row->getSourceProperty('instances');
      switch ($instances[0]['bundle']) {
        case 'OLD_BUNDLE':
          $instances[0]['bundle'] = 'NEW_BUNDLE';
          // Merge fields to person type.
          $row->setSourceProperty('instances', $instances);
          break;
      }

      // Move a field to a new type / bundle example continued.
      $bundle = $row->getSourceProperty('bundle');
      switch ($bundle) {
        case 'OLD_BUNDLE':
          $row->setSourceProperty('bundle', 'NEW_BUNDLE');
          // Merge fields to person type.
          break;
      }

      if ($migration->id() === 'upgrade_d7_field_formatter_settings') {
        // Some typical legacy formatter type conversions.
        $formatter = $row->getSourceProperty('formatter');
        switch ($formatter['type']) {
          case 'taxonomy_term_reference_plain':
            $formatter['type'] = 'entity_reference_label';
            $row->setSourceProperty('formatter', $formatter);
            break;

          case 'text_plain':
            $formatter['type'] = 'basic_string';
            $row->setSourceProperty('formatter', $formatter);
            break;

          case 'link_plain':
            $formatter['type'] = 'link_default';
            $row->setSourceProperty('formatter', $formatter);
            break;

          case 'file_rendered':
            $formatter['type'] = 'entity_reference_entity_view';
            $row->setSourceProperty('formatter', $formatter);
            break;

          case 'rss_enclosure':
            $formatter['type'] = 'file_rss_enclosure';
            $row->setSourceProperty('formatter', $formatter);
            break;
        }
      }

      if ($migration->id() === 'upgrade_d7_field_instance_widget_settings') {
        // Adjust a widget type example.
        $widget = $row->getSourceProperty('widget');
        switch ($widget['type']) {
          case 'inline_entity_form':
            $widget['type'] = 'inline_entity_form_simple';
            $row->setSourceProperty('widget', $widget);
            break;
        }
      }
      break;

    case 'upgrade_d7_profile2_informacion_privada_alta_feap':
      $pid = $row->getSourceProperty('pid');

      $feap_tids = [
        1082, 1083, 744
      ];

      $tids = $row->getSourceProperty('field_tipo_de_miembro');
      $tid_vals = [];

      foreach ($tids as $k => $tid) {
        $tid_vals[] = $tid['tid'];
        if (!in_array($tid['tid'], $feap_tids)) {
          unset($tids[$k]);
        }
      }

      // Skip all non-FEAP tids.
      if (empty(array_intersect($tid_vals, $feap_tids))) {
        throw new MigrateSkipRowException('Source pid: ' . $pid, TRUE);
      }
      // Update source only with FEAP terms.
      $row->setSourceProperty('field_tipo_de_miembro', $tids);

    break;

    case 'upgrade_d7_user':
    case 'upgrade_d7_profile2_informacion_privada':
      $address = $row->getSourceProperty('field_domicilio_particular');
      if (!empty($address) && (!isset($address[0]['country']) || !$address[0]['country'])) {
        // Suppress migration error if the address is empty.
        $row->setSourceProperty('field_domicilio_particular', []);
      }
    break;

    case 'upgrade_d7_node_complete_notica_body_to_paragraph':
      $type = $row->getSourceProperty('type');
      // Skip all nodes except noticia.
      if ($type != 'noticia') {
        throw new MigrateSkipRowException('', TRUE);
      }
      break;

    case 'upgrade_d7_profile2_informacion_profesional':
      $name = $row->getSourceProperty('field_nombre_proff');
      $lastname = $row->getSourceProperty('field_apellidos_prof');
      $row->setSourceProperty('field_nombre_proff', $name[0]['value'] . ' ' . $lastname[0]['value']);
      break;

    case 'upgrade_d7_node_complete_recurso':
    case 'upgrade_d7_node_complete_recurso_body_to_paragraph':
      $tid = $row->getSourceProperty('field_tipo_de_recurso');
      $nid = $row->getSourceProperty('nid');

      if (!isset($tid[0]["tid"])) {
        throw new MigrateSkipRowException('Source nid: ' . $nid, TRUE);
      }
      // Skip all nodes except Tesina tid = 50.
      if ($tid[0]["tid"] != 50) {
        throw new MigrateSkipRowException('', TRUE);
      }
      break;

    case 'upgrade_d7_profile2_informacion_privada_insurance':
      $tid = $row->getSourceProperty('field_seguro_mapfre');
      $pid = $row->getSourceProperty('pid');

      if (!isset($tid[0]["tid"])) {
        throw new MigrateSkipRowException('Source pid: ' . $pid, TRUE);
      }
      if ($tid[0]["tid"] == 935) {
        throw new MigrateSkipRowException('', TRUE);
      }
      break;
  }
}
