<?php

/**
 * @file
 * Contains aetg_cart.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\aetg_cart\Form\AetgAddToCartForm;

/**
 * Implements hook_help().
 */
function aetg_cart_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.aetg_cart':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides cart functionality.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_build().
 */
function aetg_cart_entity_type_build(array &$entity_types) {
  $operations = ['add_to_cart',];
  foreach ($operations as $operation) {
    /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
    $entity_types['commerce_order_item']->setFormClass($operation, AetgAddToCartForm::class);
  }
}
